// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace Mangle.Native
{
    internal static unsafe partial class NativeMethods
    {
        const string __DllName = "mangle_ffi";





        /// <summary>
        ///  Write the library's semantic version as a UTF-8 string into `out`.
        ///
        ///  Always succeeds unless `out` is null. The returned buffer is owned
        ///  by the caller and must be released with [`mangle_buffer_free`].
        ///
        ///  # Safety
        ///  `out` must be non-null and point to a writable [`MangleBuffer`].
        /// </summary>
        [DllImport(__DllName, EntryPoint = "mangle_version", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int mangle_version(MangleBuffer* @out);

        /// <summary>
        ///  Release a [`MangleBuffer`] previously produced by the library.
        ///
        ///  Safe to call with a null pointer or a zeroed/empty buffer (both
        ///  no-ops). After return, the buffer's fields are zeroed so a subsequent
        ///  double-free is also a no-op.
        ///
        ///  # Safety
        ///  If `buf` is non-null, it must point to a buffer that was produced by
        ///  this library and has not been freed. The buffer's `data`/`len`/`cap`
        ///  fields must not have been modified by the caller.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "mangle_buffer_free", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void mangle_buffer_free(MangleBuffer* buf);

        /// <summary>
        ///  Copy the current thread-local error message into `out` and clear it.
        ///
        ///  Returns [`MANGLE_OK`] regardless of whether an error was set; the
        ///  resulting buffer will be empty (zero-length, possibly null `data`)
        ///  when there was nothing to report. Calling this in a no-error state
        ///  is the canonical way to check + clear.
        ///
        ///  # Safety
        ///  `out` must be non-null and point to a writable [`MangleBuffer`].
        /// </summary>
        [DllImport(__DllName, EntryPoint = "mangle_last_error", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int mangle_last_error(MangleBuffer* @out);

        /// <summary>
        ///  Construct a new engine.
        ///
        ///  `enable_provenance` is nonzero to record derivation provenance during
        ///  rule evaluation (M9 surface); zero disables it. The flag is captured
        ///  here and consulted when rules are loaded.
        ///
        ///  On success, writes the engine pointer to `*out` and returns
        ///  [`MANGLE_OK`]. The caller owns the handle and must release it with
        ///  [`mangle_engine_free`].
        ///
        ///  # Safety
        ///  `out` must be non-null and point to writable storage for a
        ///  `*mut MangleEngine`.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "mangle_engine_new", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int mangle_engine_new(int enable_provenance, MangleEngine** @out);

        /// <summary>
        ///  Release an engine produced by [`mangle_engine_new`].
        ///
        ///  Safe to call on a null pointer or a poisoned engine. After return,
        ///  the pointer must not be used again. The drop is wrapped in
        ///  `catch_unwind` so an internal panic during drop cannot propagate
        ///  across the FFI boundary; any panic message is recorded as the
        ///  thread-local error.
        ///
        ///  # Safety
        ///  If `engine` is non-null, it must point to a handle previously
        ///  produced by [`mangle_engine_new`] that has not already been freed.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "mangle_engine_free", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void mangle_engine_free(MangleEngine* engine);

        /// <summary>
        ///  Compile and execute one or more Mangle source units, replacing any
        ///  previously loaded program.
        ///
        ///  `sources` is an array of `n_sources` pointers; `lens` parallels it
        ///  with the byte length of each source. Each source is treated as
        ///  UTF-8.
        ///
        ///  On success, returns [`MANGLE_OK`] and bumps the engine's generation
        ///  counter (any cursors opened against the previous generation will
        ///  refuse subsequent reads). On parse / type-check / evaluation
        ///  failure, the engine's previous state is preserved unchanged and a
        ///  nonzero status is returned with the formatted error available via
        ///  [`mangle_last_error`].
        ///
        ///  # Safety
        ///  `engine` must be a live handle from [`mangle_engine_new`].
        ///  `sources` and `lens` must point to readable arrays of `n_sources`
        ///  elements; each `sources[i]` must point to `lens[i]` readable bytes
        ///  of UTF-8.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "mangle_load_rules", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int mangle_load_rules(MangleEngine* engine, byte** sources, nuint* lens, nuint n_sources);

        /// <summary>
        ///  Insert a tuple as a fact in the named relation.
        ///
        ///  `tuple` is an array of `arity` borrowed `MangleVal` handles. The
        ///  values are cloned into the engine's store; the source handles
        ///  remain owned by their producer (typically a [`MangleValBuilder`]).
        ///
        ///  On success, `*added_out` (if non-null) is set to 1 when the tuple
        ///  was new and 0 when the relation already contained it. The store's
        ///  scan-visible set is updated atomically: subsequent `mangle_query`
        ///  calls see the new tuple.
        ///
        ///  **IDB relations are not re-derived.** Inserting a tuple into a
        ///  relation that is the head of one or more rules does not cause
        ///  those rules to fire on the new fact. To re-evaluate the IDB,
        ///  reload the rules with [`mangle_load_rules`]. This mirrors mangle-py
        ///  (`PyProgram::insert`).
        ///
        ///  Returns [`MANGLE_OK`] on success, [`MANGLE_ERR_NO_RULES`] when no
        ///  program is loaded, [`MANGLE_ERR_INVALID_ARG`] for null/invalid
        ///  inputs, or [`MANGLE_ERR`] for a store-level failure.
        ///
        ///  # Safety
        ///  `engine` must be a live handle. `relation` must point to
        ///  `relation_len` readable UTF-8 bytes. `tuple` must point to `arity`
        ///  readable `*const MangleVal` entries; each entry must be a live
        ///  handle. `added_out` is nullable.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "mangle_insert_fact", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int mangle_insert_fact(MangleEngine* engine, byte* relation, nuint relation_len, Value** tuple, nuint arity, int* added_out);

        /// <summary>
        ///  Retract a tuple from the named relation.
        ///
        ///  `*found_out` (if non-null) is set to 1 if the tuple was present and
        ///  removed, 0 otherwise. Operates on the stable set; no merge_deltas
        ///  is needed.
        ///
        ///  Like insert, IDB relations are not automatically reconciled — a
        ///  retracted EDB fact whose absence would invalidate derived facts
        ///  leaves stale IDB tuples in place until rules are reloaded.
        ///
        ///  # Safety
        ///  Same as [`mangle_insert_fact`].
        /// </summary>
        [DllImport(__DllName, EntryPoint = "mangle_retract_fact", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int mangle_retract_fact(MangleEngine* engine, byte* relation, nuint relation_len, Value** tuple, nuint arity, int* found_out);

        /// <summary>
        ///  Open a cursor over the tuples matching `query`.
        ///
        ///  `query` is a Mangle atom: a bare predicate name like `reachable`,
        ///  or `pred(arg1, ...)` with constants used as equality filters and
        ///  uppercase identifiers acting as wildcards. See
        ///  [`crate::query::parse_query_lenient`] for the exact syntax.
        ///
        ///  Returns [`MANGLE_OK`] on success and writes the cursor pointer to
        ///  `*out`. Returns [`MANGLE_ERR_NO_RULES`] if the engine has no
        ///  program loaded, [`MANGLE_ERR_PARSE`] for a malformed query, or
        ///  [`MANGLE_ERR`] if the named relation does not exist in the store.
        ///
        ///  The cursor must be released with [`mangle_cursor_free`] (which is
        ///  safe to call in any order with respect to engine free). Calling
        ///  [`mangle_cursor_next`] requires the engine to still be alive.
        ///
        ///  # Safety
        ///  `engine` must be a live handle. `query` must point to `query_len`
        ///  readable UTF-8 bytes (or be null with `query_len == 0`). `out` must
        ///  be non-null and point to writable storage for a `*mut MangleCursor`.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "mangle_query", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int mangle_query(MangleEngine* engine, byte* query, nuint query_len, MangleCursor** @out);

        /// <summary>
        ///  Advance the cursor to the next row.
        ///
        ///  Returns:
        ///    - [`MANGLE_OK`] (0) when a row was produced; access columns via
        ///      [`mangle_cursor_arity`] and [`mangle_cursor_col`].
        ///    - `1` when the cursor has reached end-of-stream. Further calls
        ///      also return `1`.
        ///    - [`MANGLE_ERR_CURSOR_INVALIDATED`] when the engine has been
        ///      reloaded or poisoned since the cursor was opened. The cursor
        ///      handle is still safe to free but yields no more rows.
        ///    - [`MANGLE_ERR_INVALID_ARG`] when `cursor` is null.
        ///
        ///  # Safety
        ///  `cursor` must be a live cursor. The engine that produced it must be
        ///  alive at the time of the call (it is dereferenced to read the
        ///  generation counter); calling this after `mangle_engine_free` on
        ///  the producing engine is undefined behavior.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "mangle_cursor_next", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int mangle_cursor_next(MangleCursor* cursor);

        /// <summary>
        ///  Report the arity (column count) of the current row.
        ///
        ///  Returns the column count when a row is loaded (after a successful
        ///  [`mangle_cursor_next`]). Returns `0` when no row is loaded
        ///  (before first call or after end-of-stream). Returns `-1` if
        ///  `cursor` is null.
        ///
        ///  # Safety
        ///  `cursor` must be null or a live cursor.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "mangle_cursor_arity", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int mangle_cursor_arity(MangleCursor* cursor);

        /// <summary>
        ///  Borrowed handle to the column at `col_idx` in the current row.
        ///
        ///  Returns null if `cursor` is null, no row is loaded, or the index is
        ///  out of range. The returned handle borrows from the cursor's
        ///  current-row buffer and is valid until the next call to
        ///  [`mangle_cursor_next`] or [`mangle_cursor_free`] on this cursor.
        ///
        ///  # Safety
        ///  `cursor` must be null or a live cursor.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "mangle_cursor_col", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern Value* mangle_cursor_col(MangleCursor* cursor, uint col_idx);

        /// <summary>
        ///  Release a cursor.
        ///
        ///  Safe to call on null. Safe to call regardless of the producing
        ///  engine's state (the cursor's row data is owned, not borrowed; this
        ///  function does not dereference the stored engine pointer).
        ///
        ///  # Safety
        ///  If `cursor` is non-null, it must point to a cursor previously
        ///  returned by [`mangle_query`] that has not already been freed.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "mangle_cursor_free", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void mangle_cursor_free(MangleCursor* cursor);

        /// <summary>
        ///  Bulk-load facts from a `.mgr` byte slice into the engine.
        ///
        ///  `bytes` is a SimpleRow byte stream as produced by
        ///  `mangle_db::simplerow::write_simple_row` (M7), optionally
        ///  compressed with gzip or zstd (auto-detected via magic bytes).
        ///
        ///  `source_name` is a human-readable identifier (e.g. a file path)
        ///  included verbatim in error messages. May be empty.
        ///
        ///  On success, returns [`MANGLE_OK`] and writes the number of
        ///  inserted tuples (including duplicates) into `*n_inserted_out` if
        ///  non-null. The store's scan-visible set is updated atomically;
        ///  subsequent queries see all loaded tuples. Returns
        ///  [`MANGLE_ERR_NO_RULES`] when the engine has no program loaded
        ///  (load rules first), [`MANGLE_ERR_PARSE`] when the byte stream
        ///  isn't a valid `.mgr`, [`MANGLE_ERR_INVALID_ARG`] for null pointers
        ///  or invalid UTF-8 in `source_name`, or [`MANGLE_ERR`] for other
        ///  failures (decompression error, store-level insert failure).
        ///
        ///  IDB relations are not re-derived — see [`mangle_insert_fact`] for
        ///  the same caveat.
        ///
        ///  # Safety
        ///  `engine` must be a live handle. `bytes` must point to `len`
        ///  readable bytes (or be null with `len == 0`). `source_name` must
        ///  point to `name_len` readable UTF-8 bytes (or be null with
        ///  `name_len == 0`). `n_inserted_out` is nullable.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "mangle_load_facts_mgr", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int mangle_load_facts_mgr(MangleEngine* engine, byte* bytes, nuint len, byte* source_name, nuint name_len, nuint* n_inserted_out);

        /// <summary>
        ///  Encode every relation in the engine's store as a single SimpleRow
        ///  `.mgr` blob, optionally compressed.
        ///
        ///  Use for "Save Project" — write the resulting buffer to `facts.mgr`
        ///  (or `facts.mgr.gz` if `compression == MANGLE_COMPRESSION_GZIP`).
        ///
        ///  Returns [`MANGLE_OK`] on success; the resulting buffer is owned by
        ///  the caller and must be freed with [`mangle_buffer_free`]. Returns
        ///  [`MANGLE_ERR_NO_RULES`] when no program is loaded,
        ///  [`MANGLE_ERR_INVALID_ARG`] for null `out` or an unsupported
        ///  compression mode (currently `MANGLE_COMPRESSION_ZSTD`), or
        ///  [`MANGLE_ERR`] for store-side or encoding failures.
        ///
        ///  # Safety
        ///  `engine` must be a live handle. `out` must be non-null and point to
        ///  a writable [`MangleBuffer`].
        /// </summary>
        [DllImport(__DllName, EntryPoint = "mangle_save_facts_mgr", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int mangle_save_facts_mgr(MangleEngine* engine, int compression, MangleBuffer* @out);

        /// <summary>
        ///  Encode a single named relation as a SimpleRow `.mgr` blob,
        ///  optionally compressed. Useful for per-relation backups or exports.
        ///
        ///  Returns [`MANGLE_ERR`] if the relation does not exist in the store;
        ///  other error codes match [`mangle_save_facts_mgr`].
        ///
        ///  # Safety
        ///  `engine` must be a live handle. `relation` must point to
        ///  `relation_len` readable UTF-8 bytes. `out` must be non-null.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "mangle_save_relation_mgr", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int mangle_save_relation_mgr(MangleEngine* engine, byte* relation, nuint relation_len, int compression, MangleBuffer* @out);

        /// <summary>
        ///  Run a query and encode the matching tuples as a SimpleRow `.mgr`
        ///  blob under the caller-supplied relation name `out_relation`.
        ///
        ///  Useful for "Export Query Result" — the user types `route("GET",
        ///  Path)`, the workbench produces a downloadable `.mgr` file where
        ///  the matching tuples live under a relation named e.g.
        ///  `get_routes`. The output relation name is independent of the
        ///  queried predicate, so it can be anything the consumer wants.
        ///
        ///  Query syntax matches [`mangle_query`].
        ///
        ///  # Safety
        ///  `engine` must be a live handle. `query` must point to `query_len`
        ///  readable UTF-8 bytes. `out_relation` must point to
        ///  `out_relation_len` readable UTF-8 bytes (must be non-empty). `out`
        ///  must be non-null.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "mangle_query_dump_mgr", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int mangle_query_dump_mgr(MangleEngine* engine, byte* query, nuint query_len, byte* out_relation, nuint out_relation_len, int compression, MangleBuffer* @out);

        /// <summary>
        ///  Emit the engine's schema as a JSON document.
        ///
        ///  Shape:
        ///  ```json
        ///  {
        ///    "predicates": [
        ///      { "name": "edge", "arity": 2, "type_args": null, "kind": "edb" },
        ///      { "name": "reachable", "arity": 2, "type_args": null, "kind": "idb" }
        ///    ],
        ///    "rules": [
        ///      { "rule_id": 0, "head": "reachable", "body": ["edge"] },
        ///      { "rule_id": 1, "head": "reachable", "body": ["edge", "reachable"] }
        ///    ]
        ///  }
        ///  ```
        ///
        ///  `kind` is `"edb"` or `"idb"` based on whether the predicate has
        ///  any defining rules. `type_args` will populate in a later milestone
        ///  when the Ir's `Decl.bounds` walker is wired up; for now it's
        ///  `null`.
        ///
        ///  Returns [`MANGLE_OK`] on success; the buffer is owned by the
        ///  caller and must be released with `mangle_buffer_free`. Returns
        ///  [`MANGLE_ERR_NO_RULES`] when the engine has no program loaded, or
        ///  [`MANGLE_ERR_INVALID_ARG`] for null `out`.
        ///
        ///  # Safety
        ///  `engine` must be a live handle. `out` must be non-null.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "mangle_schema_snapshot", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int mangle_schema_snapshot(MangleEngine* engine, MangleBuffer* @out);

        /// <summary>
        ///  Emit the sorted list of declared predicate names as a JSON array.
        ///
        ///  Cheap alternative to [`mangle_schema_snapshot`] when you only need
        ///  the picker UI's relation dropdown — no arity, no rule edges, just
        ///  the names.
        ///
        ///  # Safety
        ///  `engine` must be a live handle. `out` must be non-null.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "mangle_relation_names", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int mangle_relation_names(MangleEngine* engine, MangleBuffer* @out);

        /// <summary>
        ///  Emit a "facts overview" snapshot — every declared relation with its
        ///  arity, kind (EDB/IDB), current tuple count, and at most
        ///  `per_relation_limit` sample tuples.
        ///
        ///  Output shape:
        ///  ```json
        ///  {
        ///    "relations": [
        ///      {
        ///        "name": "edge",
        ///        "arity": 2,
        ///        "kind": "edb",
        ///        "count": 12345,
        ///        "sample": [
        ///          { "tuple": [1, 2] },
        ///          { "tuple": [2, 3] }
        ///        ]
        ///      }
        ///    ]
        ///  }
        ///  ```
        ///
        ///  Relations come from the schema cache so declared-but-empty
        ///  predicates also appear (with `count: 0, sample: []`). Tuple
        ///  elements use the same value-to-JSON encoding as
        ///  `mangle_derivation_tree` — scalars as primitives,
        ///  `Name`/`Time`/`Duration`/`Compound` as tagged objects (lossy but
        ///  unambiguous for visualization).
        ///
        ///  `per_relation_limit = 0` means "don't include any samples, just
        ///  counts." Pass `UINT32_MAX` for "include everything" (workbench-
        ///  scale only — large stores should use the batch-encode endpoints
        ///  instead).
        ///
        ///  # Safety
        ///  `engine` must be a live handle. `out` must be non-null.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "mangle_facts_snapshot", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int mangle_facts_snapshot(MangleEngine* engine, uint per_relation_limit, MangleBuffer* @out);

        /// <summary>
        ///  Emit the derivation tree for a given fact as JSON.
        ///
        ///  The fact is parsed as a Mangle atom — same syntax as queries (see
        ///  `mangle_query`) — but variables aren't allowed: the fact must be
        ///  fully ground.
        ///
        ///  Requires the engine was constructed with `enable_provenance = 1`.
        ///  Returns:
        ///  - [`MANGLE_OK`] on success; JSON buffer owned by caller.
        ///  - [`MANGLE_ERR_NO_RULES`] when no program is loaded.
        ///  - [`MANGLE_ERR_NO_PROVENANCE`] when the engine was built without
        ///    provenance.
        ///  - [`MANGLE_ERR_PARSE`] for a malformed atom or a variable arg.
        ///  - [`MANGLE_ERR_FACT_NOT_FOUND`] when the fact has no recorded
        ///    derivations (EDB facts with no IDB consumers may not appear at
        ///    all in the provenance index; user typos likewise).
        ///  - [`MANGLE_ERR_INVALID_ARG`] for null pointers.
        ///
        ///  `max_depth` is the maximum nesting depth of the returned tree.
        ///  Use `0xFFFF_FFFF` (`UINT32_MAX`) for unlimited.
        ///
        ///  # Safety
        ///  `engine` must be a live handle. `fact` must point to `len`
        ///  readable UTF-8 bytes. `out` must be non-null.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "mangle_derivation_tree", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int mangle_derivation_tree(MangleEngine* engine, byte* fact, nuint len, uint max_depth, MangleBuffer* @out);

        /// <summary>
        ///  Report the kind tag of a value.
        ///
        ///  Returns one of the `MANGLE_VAL_*` constants. Returns `-1` if `v` is
        ///  null or accessing it panics.
        ///
        ///  # Safety
        ///  If `v` is non-null, it must point to a live `MangleVal` borrowed
        ///  from a producer (builder or cursor row) that has not been freed.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "mangle_val_kind", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int mangle_val_kind(Value* v);

        /// <summary>
        ///  Extract an `i64` from a `Number`, `Time`, or `Duration` value.
        ///
        ///  Returns [`MANGLE_OK`] on success. Returns [`MANGLE_ERR_INVALID_ARG`]
        ///  for null inputs and [`MANGLE_ERR`] for a wrong-kind value (with the
        ///  last_error slot populated).
        ///
        ///  # Safety
        ///  `v` and `out` must be non-null and live.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "mangle_val_as_i64", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int mangle_val_as_i64(Value* v, long* @out);

        /// <summary>
        ///  Extract an `f64` from a `Float` value.
        ///
        ///  # Safety
        ///  `v` and `out` must be non-null and live.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "mangle_val_as_f64", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int mangle_val_as_f64(Value* v, double* @out);

        /// <summary>
        ///  Copy the textual content of a `String` or `Name` value into `out`.
        ///
        ///  For a `Name`, the leading `/` is **kept** — consumers that want it
        ///  stripped should slice the buffer after the call. (Keeping it
        ///  preserves the round-trip property: `build_name(as_str(name))` is the
        ///  identity.)
        ///
        ///  # Safety
        ///  `v` and `out` must be non-null and live.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "mangle_val_as_str", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int mangle_val_as_str(Value* v, MangleBuffer* @out);

        /// <summary>
        ///  Report the compound subkind of a compound value.
        ///
        ///  # Safety
        ///  `v` and `subkind_out` must be non-null and live.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "mangle_val_compound_kind", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int mangle_val_compound_kind(Value* v, int* subkind_out);

        /// <summary>
        ///  Report the number of items (for `List`/`Pair`) or pairs (for
        ///  `Map`/`Struct`) in a compound value.
        ///
        ///  For maps and structs, the underlying flat vector has `2*N` entries
        ///  for `N` pairs; this function returns `N`, not `2*N`.
        ///
        ///  # Safety
        ///  `v` and `out` must be non-null and live.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "mangle_val_compound_len", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int mangle_val_compound_len(Value* v, nuint* @out);

        /// <summary>
        ///  Borrowed handle to a compound element at the given linear index.
        ///
        ///  Use this for `List`/`Pair` values. For `Map`/`Struct`, use
        ///  [`mangle_val_compound_kv`] instead — the indexing semantics differ
        ///  (pair index vs. flat index).
        ///
        ///  Returns `null` if `v` is null, not a compound, or the index is out
        ///  of range. The returned handle borrows from the same producer as
        ///  `v`; do not outlive it.
        ///
        ///  # Safety
        ///  `v` must be null or a live handle.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "mangle_val_compound_get", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern Value* mangle_val_compound_get(Value* v, nuint index);

        /// <summary>
        ///  Borrowed handles to the key and value at a given pair index in a
        ///  `Map` or `Struct` value.
        ///
        ///  `pair_index` is in `0..N` where `N` is `mangle_val_compound_len`.
        ///  The underlying flat vector positions are `2 * pair_index` (key) and
        ///  `2 * pair_index + 1` (value).
        ///
        ///  # Safety
        ///  `v`, `key_out`, and `val_out` must be non-null and live.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "mangle_val_compound_kv", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int mangle_val_compound_kv(Value* v, nuint pair_index, Value** key_out, Value** val_out);

        /// <summary>
        ///  Construct a new value builder. Returns null on allocation failure
        ///  (which is currently unreachable, but the C ABI consumer should still
        ///  check). Release with [`mangle_val_builder_free`].
        ///
        ///  # Safety
        ///  Safe to call from any context; the `unsafe` marker is for ABI
        ///  consistency with the other entry points in this crate.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "mangle_val_builder_new", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern MangleValBuilder* mangle_val_builder_new();

        /// <summary>
        ///  Release a builder. All handles previously returned by `build_*`
        ///  against this builder become invalid; using them after this call is
        ///  UB. Passing null is a no-op.
        ///
        ///  # Safety
        ///  If `b` is non-null, it must point to a builder previously returned
        ///  by [`mangle_val_builder_new`] that has not already been freed.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "mangle_val_builder_free", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void mangle_val_builder_free(MangleValBuilder* b);

        /// <summary>
        ///  Build a `Null` value.
        ///
        ///  # Safety
        ///  `b` must be a live builder.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "mangle_val_build_null", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern Value* mangle_val_build_null(MangleValBuilder* b);

        /// <summary>
        ///  Build a `Number` value from an `i64`.
        ///
        ///  # Safety
        ///  `b` must be a live builder.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "mangle_val_build_i64", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern Value* mangle_val_build_i64(MangleValBuilder* b, long n);

        /// <summary>
        ///  Build a `Float` value from an `f64`.
        ///
        ///  # Safety
        ///  `b` must be a live builder.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "mangle_val_build_f64", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern Value* mangle_val_build_f64(MangleValBuilder* b, double f);

        /// <summary>
        ///  Build a `Time` value from i64 nanoseconds since the Unix epoch.
        ///
        ///  # Safety
        ///  `b` must be a live builder.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "mangle_val_build_time_ns", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern Value* mangle_val_build_time_ns(MangleValBuilder* b, long nanos);

        /// <summary>
        ///  Build a `Duration` value from i64 nanoseconds.
        ///
        ///  # Safety
        ///  `b` must be a live builder.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "mangle_val_build_duration_ns", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern Value* mangle_val_build_duration_ns(MangleValBuilder* b, long nanos);

        /// <summary>
        ///  Build a `String` value from a UTF-8 byte slice. Returns null and
        ///  sets last_error on invalid UTF-8.
        ///
        ///  # Safety
        ///  `b` must be live. `s` must point to `len` readable bytes (or be null
        ///  with `len == 0`).
        /// </summary>
        [DllImport(__DllName, EntryPoint = "mangle_val_build_string", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern Value* mangle_val_build_string(MangleValBuilder* b, byte* s, nuint len);

        /// <summary>
        ///  Build a `Name` value from a UTF-8 byte slice.
        ///
        ///  Mangle name constants must start with `/`; otherwise this returns
        ///  null and populates `last_error`. (Matches mangle-py's `PyName::new`
        ///  contract.)
        ///
        ///  # Safety
        ///  `b` must be live. `s` must point to `len` readable bytes (or be null
        ///  with `len == 0`).
        /// </summary>
        [DllImport(__DllName, EntryPoint = "mangle_val_build_name", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern Value* mangle_val_build_name(MangleValBuilder* b, byte* s, nuint len);

        /// <summary>
        ///  Build a compound value (`List`, `Pair`, `Map`, or `Struct`) by
        ///  cloning the given element handles into a new `Value::Compound`.
        ///
        ///  `subkind` selects the compound kind via the `MANGLE_COMPOUND_*`
        ///  constants. For `Map` and `Struct`, `elems` is a flat `[k0, v0, k1,
        ///  v1, ...]` sequence and `n` is the total entry count (so `n` must be
        ///  even).
        ///
        ///  Element handles must point to values living in the same builder (or
        ///  in any other producer with stable lifetime through this call); they
        ///  are cloned, not aliased, so the originals can be freed independently
        ///  of the resulting compound.
        ///
        ///  Returns null and sets last_error on bad subkind, bad element
        ///  pointer, or odd `n` for map/struct.
        ///
        ///  # Safety
        ///  `b` must be live. `elems` must point to `n` readable `*const MangleVal`
        ///  entries; each non-null entry must reference a live value.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "mangle_val_build_compound", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern Value* mangle_val_build_compound(MangleValBuilder* b, int subkind, Value** elems, nuint n);


    }

    /// <summary>
    ///  A heap-allocated byte buffer owned by the caller.
    ///
    ///  Returned by FFI entry points that produce variable-length output. The
    ///  caller must release it with [`mangle_buffer_free`]. A zeroed
    ///  `MangleBuffer` (all fields 0/null) is the canonical "empty / released"
    ///  state; freeing it is a no-op.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct MangleBuffer
    {
        public byte* data;
        public nuint len;
        public nuint cap;
    }

    /// <summary>
    ///  Opaque engine handle.
    ///
    ///  The flag and counter fields are `pub(crate)` so the
    ///  `panic_boundary!` macro can read/mutate them directly; consumers see
    ///  only an opaque pointer through the C ABI.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct MangleEngine
    {
    }

    /// <summary>
    ///  Query result cursor.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct MangleCursor
    {
    }

    /// <summary>
    ///  Arena owning a set of `Value`s constructed via the `build_*` entry
    ///  points. Hands out `*const MangleVal` handles that are valid until
    ///  the builder is freed.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct MangleValBuilder
    {
    }



}
